hq:
  swagger-open: true
  spring-session-open: false
  muti-datasource:
  open: false
  url: jdbc:mysql://127.0.0.1:3306/finan?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
  username: root
  password: 123456

server:
  port: 80

spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false #\u7F13\u5B58\u914D\u7F6E
    template-loader-path: classpath:/templates/views  #\u6A21\u677F\u52A0\u8F7D\u8DEF\u5F84
    charset: utf-8 #\u7F16\u7801\u683C\u5F0F
    settings:
      number_format: '0.##' #\u6570\u5B57\u683C\u5F0F\u5316\uFF0C\u65E0\u5C0F\u6570\u70B9
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
  session:
    store-type: mongodb


mybatis-plus:
  type-aliases-package: com.hq.financial.web.entity
  mapper-locations: classpath*:com/hq/financial/web/dao/mapping/*.xml
  global-config:
    id-type: 0  #0:\u6570\u636E\u5E93ID\u81EA\u589E   1:\u7528\u6237\u8F93\u5165id  2:\u5168\u5C40\u552F\u4E00id(IdWorker)  3:\u5168\u5C40\u552F\u4E00ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false #\u914D\u7F6E\u5168\u5C40\u7684\u7F13\u5B58\u5F00\u5173
    lazy-loading-enabled: true #\u5F00\u542F\u7684\u8BDD\uFF0C\u5EF6\u65F6\u52A0\u8F7D\u4E00\u4E2A\u5C5E\u6027\u65F6\u4F1A\u52A0\u8F7D\u8BE5\u5BF9\u8C61\u5168\u90E8\u5C5E\u6027\uFF0C\u5426\u5219\u6309\u9700\u52A0\u8F7D\u5C5E\u6027
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u6253\u5370sql\u8BED\u53E5,\u8C03\u8BD5\u7528
logging:
  level:
    org.springframework.web: debug #\u65E5\u5FD7\u7EA7\u522B
  file:  /opt/logs/financial.log #\u65E5\u5FD7\u6587\u4EF6





